### ISSUE TITLE
Error on Debian Buster

### ISSUE THREAD

**Issue by roguephysicist** [franko/regress-pro#2]
Hi,

I'm trying to compile on Debian Buster, that provides libagg 2.6 by default. Is Regress Pro compatible with this new version? I have included the error that occurs when running make. 

Thanks
[error.txt](https://github.com/franko/regress-pro/files/3553611/error.txt)

**Comment by franko** [comment]
Hi,

maybe you are using a slightly outdated version of regress pro. I recommend to use the master branch from the github repository.

I tried to compile right now on ubuntu and it works. I am also almost sure that the error you got is not due to agg but to regress-pro itself. I fixed this some time ago but I do not remember exactly.

So, please test again the master branch from github.

**Comment by roguephysicist** [comment]
Hi,

Nope, I cloned the repo directly. I also tried it with the source code included in release v2.1.0-beta2, but the same thing happened.

I am using Debian Buster with:

libgsl-dev           2.5+dfsg-6
libfox-1.6-dev    1.6.57-1 
libagg2-dev       1:2.6.0-r132+dfsg1-3

Thanks.

**Comment by franko** [comment]
Ok, I think I have it. The following change should fix that:

```diff
diff --git a/fox-gui/vs_object.h b/fox-gui/vs_object.h
index ad84403..24a62c7 100644
--- a/fox-gui/vs_object.h
+++ b/fox-gui/vs_object.h
@@ -48,7 +48,7 @@ public:
     }
 
     virtual void apply_transform(const agg::trans_affine& m, double as) {
-        m_trans.transformer(m);
+        m_mtx = m;
     }
 
     virtual void bounding_box(double *x1, double *y1, double *x2, double *y2) {
```

**Comment by roguephysicist** [comment]
Hey,

I also had to change this to get it to work:

```diff
diff --git a/fox-gui/disp_vs.h b/fox-gui/disp_vs.h
index 394084c..d8d7b1b 100644
--- a/fox-gui/disp_vs.h
+++ b/fox-gui/disp_vs.h
@@ -56,7 +56,7 @@ public:
     }
 
     virtual void apply_transform(const agg::trans_affine& m, double as) {
-        m_trans.transformer(m);
+        m_mtx = m;
     }
 
     virtual void bounding_box(double *x1, double *y1, double *x2, double *y2) {
```

Thanks for the help!

**Comment by franko** [comment]
Thanks to you, Rogue Physicist, for testing :-)

The fix is now on the master branch. Otherwise I checked and the fix was already on the dev branch.

I hope Regress Pro will works for you!
